/*
 * Power of attorney
 * This is a sample server power of attorney service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.kraaknet.poatapi.backend.http.model;

import lombok.Getter;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Getter
@RequiredArgsConstructor
public enum Authorization {
  
  DEBIT_CARD("DEBIT_CARD"),
  CREDIT_CARD("CREDIT_CARD"),
  VIEW("VIEW"),
  PAYMENT("PAYMENT");

  @NonNull
  private final String value;
  
}

